// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import BulkSelectController from "./bulk_select_controller"
application.register("bulk-select", BulkSelectController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import ShortcutsController from "./shortcuts_controller"
application.register("shortcuts", ShortcutsController)

import TopbarSearchController from "./topbar_search_controller"
application.register("topbar-search", TopbarSearchController)

import DataTableController from "./data_table_controller"
application.register("data-table", DataTableController)

import LoadingButtonController from "./loading_button_controller"
application.register("loading-button", LoadingButtonController)

import PipelineBoardController from "./pipeline_board_controller"
application.register("pipeline-board", PipelineBoardController)

import ToggleSectionController from "./toggle_section_controller"
application.register("toggle-section", ToggleSectionController)

import ConfirmToggleController from "./confirm_toggle_controller"
application.register("confirm-toggle", ConfirmToggleController)

import DirtyFormController from "./dirty_form_controller"
application.register("dirty-form", DirtyFormController)
